# DOMAIN=example.com docker stack deploy -c prestashop.yml prestashop

services:
  app:
    image: prestashop/prestashop:${VERSION:-8}
    volumes:
      - ${VOLUME_PATH}data:/var/www/html:cached
    environment:
      - DB_SERVER=mariadb
      - DB_USER=prestashop
      - DB_PASSWD=myp@ssw0rd
      - DB_NAME=prestashop
      - PS_DEV_MODE=${PS_DEV_MODE:-0}
      - PS_LANGUAGE=${PS_LANGUAGE:-fr}
      - PS_DEMO_MODE=${PS_DEMO_MODE:-0}
      - PS_ENABLE_SSL=${PS_ENABLE_SSL:-1}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO:-1}
      - PS_DOMAIN=${DOMAIN:-prestashop.localhost}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN:-admin-secure}
      - PS_FOLDER_INSTALL=${PS_FOLDER_INSTALL:-install-secure}
      - PS_HANDLE_DYNAMIC_DOMAIN=${PS_HANDLE_DYNAMIC_DOMAIN:-0}
      - ADMIN_MAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWD=${ADMIN_PASSWORD:-myp@ssw0rd}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.prestashop-${NUMBER:-1}.rule=Host(`${DOMAIN:-prestashop.localhost}`)
        - traefik.http.routers.prestashop-${NUMBER:-1}.entrypoints=${SCHEME:-https}
        - traefik.http.routers.prestashop-${NUMBER:-1}.service=prestashop-${NUMBER:-1}
        - traefik.http.routers.prestashop-${NUMBER:-1}.tls.certresolver=letsencrypt
        - traefik.http.services.prestashop-${NUMBER:-1}.loadbalancer.server.port=80
    networks:
      - internal
      - traefik

  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.6}
    volumes:
      - ${VOLUME_PATH}mariadb:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=myp@ssw0rd
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=myp@ssw0rd
    networks:
      - internal

volumes:
  data:
  mariadb:

networks:
  internal:
    driver: overlay
    attachable: true
  traefik:
    external: true
    name: traefik-net
